services:
  app:
    container_name: ${APP_NAME:-Laravel}-backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERID: ${USERID:-1000}
        GROUPID: ${GROUPID:-1000}
        USER: ${USER:-laravel}
        GROUP: ${GROUP:-laravel}
    image: 'php-8.4/app'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - '.:/var/www/html'
    networks:
      - app
    depends_on: {  }
networks:
  app:
    driver: bridge
