services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GROUPID: ${GROUPID}
        GROUP: ${GROUP}
        USERID: ${USERID}
        USER: ${USER}
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./writable:/var/www/html/writable
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      - GROUPID=${GROUPID}
      - GROUP=${GROUP}
      - USERID=${USERID}
      - USER=${USER}
